export { default as AboutEvent } from './AboutEvent/aboutevent';
export { default as AboutUs } from './AboutUs/aboutus'
export { default as Agenda } from './Agenda/agenda';
export { default as Footer } from './footer/Footer';
export { default as Hero } from './Hero/hero';
export { default as OurPartners } from './OurPartners/ourpartners';
export { default as OurSpeakers } from './OurSpekers/ourspeakers';
export { default as Shared } from './shared/shared';
export { default as TheyTrusedUs } from './TheyTrusedUs/theytrused';